#!/usr/bin/env python3
"""Lightweight anonymity and hygiene scan for the artifact package."""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DISALLOWED_FILE_NAMES = {
    ".DS_Store",
    ".env",
    "cookies.json",
}
DISALLOWED_SUFFIXES = {
    ".pyc",
    ".pyo",
}
DISALLOWED_PATH_PARTS = {
    "__pycache__",
    ".git",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
}
CONTENT_PATTERNS = {
    "absolute macOS user path": re.compile("/" + "Users" + "/"),
    "local user handle": re.compile(r"\b" + "h" + "jp" + r"\b", re.IGNORECASE),
    "workspace path": re.compile("Documents/" + "Codex/PAPER"),
    "private key": re.compile(r"BEGIN [A-Z ]*PRIVATE KEY"),
    "OpenAI-style secret": re.compile(r"sk-[A-Za-z0-9_-]{20,}"),
    "Google-style secret": re.compile(r"AIza[0-9A-Za-z_-]{20,}"),
    "GitHub token": re.compile(r"(ghp_[A-Za-z0-9_]+|github_pat_[A-Za-z0-9_]+)"),
    "auto-generated docstring marker": re.compile("Auto-" + "translated documentation"),
    "chat transcript marker": re.compile(
        r"(Chat"
        + r"GPT|AI\s+assistant|Generated by\s+(Chat"
        + r"GPT|Claude))",
        re.IGNORECASE,
    ),
}
TEXT_EXTENSIONS = {
    ".csv",
    ".json",
    ".md",
    ".py",
    ".sh",
    ".txt",
    ".toml",
    ".yaml",
    ".yml",
    ".example",
    "",
}
DISALLOWED_CSV_COLUMNS = {
    "problem_statement",
    "sample_io",
    "candidate_code",
    "generated_test",
    "observed_output_or_failure",
    "trace_excerpt",
    "annotator_rationale",
    "consensus_rationale",
    "original_event_text",
    "source_log",
    "source_event_locator",
}


def is_text_candidate(path: Path) -> bool:
    return path.suffix in TEXT_EXTENSIONS and path.stat().st_size < 5_000_000


def main() -> int:
    problems: list[str] = []
    for path in ROOT.rglob("*"):
        rel = path.relative_to(ROOT)
        parts = set(rel.parts)
        if path.is_dir():
            if path.name in DISALLOWED_PATH_PARTS:
                problems.append(f"disallowed directory: {rel}")
            continue

        if parts & DISALLOWED_PATH_PARTS:
            problems.append(f"file under disallowed directory: {rel}")
        if path.name in DISALLOWED_FILE_NAMES:
            problems.append(f"disallowed file name: {rel}")
        if path.suffix in DISALLOWED_SUFFIXES:
            problems.append(f"disallowed compiled file: {rel}")
        if "Zone.Identifier" in path.name:
            problems.append(f"Windows zone marker: {rel}")

        if not is_text_candidate(path):
            continue

        text = path.read_text(encoding="utf-8", errors="ignore")
        if path.suffix == ".csv":
            first_line = text.splitlines()[0] if text.splitlines() else ""
            columns = {item.strip() for item in first_line.split(",")}
            disallowed = sorted(columns & DISALLOWED_CSV_COLUMNS)
            if disallowed:
                problems.append(f"disallowed public CSV columns {disallowed}: {rel}")
        for name, pattern in CONTENT_PATTERNS.items():
            if pattern.search(text):
                problems.append(f"{name}: {rel}")

    if problems:
        print("Anonymity scan failed:")
        for problem in problems:
            print(f"- {problem}")
        return 1

    print("Anonymity scan passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
